### ISSUE TITLE
Docker release version checker in Image

### ISSUE THREAD

**Issue by thijsvanloef** [thijsvanloef/palworld-server-docker#493]
**Is your feature request related to a problem? Please describe.**
Create a check when the server is starting to see if the user is running the latest image (e.g. 0.31.0)
And let the user know when an upgrade is available, link to a doc that shows the user how to upgrade.

**Comment by xHyperElectric** [comment]
From some research I did yesterday it seems the only way to check what image a docker container is running from inside it is to install docker-cli inside the image and use that to check the docker sock. 
[Curl](https://forums.docker.com/t/get-a-containers-full-id-from-inside-of-itself/37237/12)
[cat /proc/self/cgroup | grep -o  -e "docker-.*.scope" | head -n 1 | sed "s/docker-\(.*\).scope/\\1/"](https://stackoverflow.com/a/25729598)

Using the /proc/self/cgroup file we could find information about the container's image and then curl docker.io to see if the current image has the same sha256 as the latest image.

This has the downside of course of adding extra bloat to the image.

The other option could be simply adding a file or a line inside a file with the current version and we could grep that file to determine the version and curl docker.io to see if there are tag versions with larger numbers than the version in the file, and if so pull latest. This file would have to be automatically updated with a GitHub action.

Which method would you prefer? @thijsvanloef 

P.S. I may be missing something, but I could not find a way to check a container's image from within without root and without installing some sort of docker-cli or otherwise inside the image.

**Comment by xHyperElectric** [comment]
> * During release/build include a txt file in the container that has the version tag of that release.
> * At container start, compare the version from that file to the Github latest release tab using the github API

Okay, awesome. This was my preferred solution. I'll think about it for a minute and submit a draft PR
