### ISSUE TITLE
Cannot use RCON

### ISSUE THREAD

**Issue by GyeongdongKim** [thijsvanloef/palworld-server-docker#70]
I deleted and reinstalled the docker container to use RCON, but it didn't work if I type "docker exec -it palworld-server rcon-cli".

Error Message:
OCI runtime exec failed: exec failed: unable to start container process: exec: "rcon-cli": executable file not found in $PATH: unknown

**Comment by thijsvanloef** [comment]
Please do the following to see if the issue persists:

- `docker stop palworld-server`
- `docker rm palworld-server`
- `docker rmi thijsvanloef/palworld-server-docker`
- `docker compose up -d`

**Comment by nizukameha** [comment]
Hello, I add env variable and restart the container but I've got : "Failed to connect to RCON serverdial tcp 127.0.0.1:25575: connect: connection refused", do you know why ?

**Comment by thijsvanloef** [comment]
@nizukameha I need some more information about your setup. But as a first troubleshooting step, did you restart the container, or removed the container, repulled the image, and started the server again?

**Comment by philipnordmann** [comment]
> Hello, I add env variable and restart the container but I've got : "Failed to connect to RCON serverdial tcp 127.0.0.1:25575: connect: connection refused", do you know why ?

@nizukameha what helped me was to delete your data directory e.g. `./palworld` and newly create the container from scratch described by @thijsvanloef
Be **very** careful since this will delete your save files.

If you don't want to do this you can copy `./palworld/DefaultPalWorldSettings.ini` to `./palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`.

Not sure why but I think before the default settings were not copied.

**Comment by nizukameha** [comment]
> @nizukameha I need some more information about your setup. But as a first troubleshooting step, did you restart the container, or removed the container, repulled the image, and started the server again?

I am using the image trought casaOS (for more context), I only restart the container, I don't removed the container because I'm scared of loosing my world. This is the content of my `PalWorldSettings.ini`

`[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575`

**Comment by shulshof** [comment]
I may be wrong but I don't it doesn't look like wget is installed and so it does not download rcon-cli:

`
root@9c870b1f18bf:/home/steam/server# wget
bash: wget: command not found
`

**Comment by thijsvanloef** [comment]
@nizukameha RCON was added in an updated version of my docker image, if you only restart the container, the new image will not be downloaded and thus, you will not be able to use RCON.

**Comment by thijsvanloef** [comment]
@shulshof if wget is not present in your container, that means you are running an older version of my image. Please update the image:

- `docker stop palworld-server`
- `docker rm palworld-server`
- `docker rmi thijsvanloef/palworld-server-docker`
- `docker compose up -d`

If you mounted the palworld folder to your system, you should not lose any data. However it is always a good idea to backup your savefiles just to be sure.

**Comment by thijsvanloef** [comment]
@GyeongdongKim Is your issue resolved and can I close this issue?

**Comment by GyeongdongKim** [comment]
> @GyeongdongKim Is your issue resolved and can I close this issue?

Yes, thank you.

**Comment by MrMysterius** [comment]
Quick, note that I found as well, when you stop the server it will save the currently loaded configuration again to the `Pal/Saved/Config/LinuxServer/PalWorldSettings.ini` config again, also the Default Configuration file `DefaultPalWorldSettings.ini` does not get loaded from my experience at all and the first config should always be used and only edited while server is stopped.
