### ISSUE TITLE
any idea of memory

### ISSUE THREAD

**Issue by larrydemons** [thijsvanloef/palworld-server-docker#8]
during the server running,the used memory went from 4g to 15g and more and idea to release the memory instead of restart the container?

**Comment by thijsvanloef** [comment]
Hi @larrydemons thank you for taking the time to create an issue. Could you give me some more information about when the memory usage increases? 

- Do the amount of players increase the memory usage?
- Does the memory increase by itself when the player count stays the same?

**Comment by larrydemons** [comment]
![QQ截图20240120191305](https://github.com/thijsvanloef/palworld-server-docker/assets/45202522/d882f5a6-5e30-4877-afd4-5097e3dfd7ce)
dont think num of ppl increase memory usage, but new mobs info or map info will do. After i got one pal it crashed so it must load it info to the memory then out of uasge.

**Comment by thijsvanloef** [comment]
My guess is that there is a memory leak in the server software, I am not sure if I can fix that, I would recommend submitting a bug report to the Pocketpair devs

**Comment by jaycewhite** [comment]
I was trying to work out how to combat this; my working theory is: I think the game just tries to eat up all available memory before freeing up any its already used.

On my 8gb home server I set a 5gb ram limit by adding the below to the docker compose, and its been happily running around the same total memory used for a while now with no crashes.

`deploy:
      mem_limit: 5g`

**Comment by jaycewhite** [comment]
Ok ignore the above, in the end while it seems to have drastically increased the time between crashes, it still did happen.

**Comment by AROAH1337** [comment]
Mine's been running for about 4 hours and is up to ~6GB of memory usage. The system requirements in the server documentation recommend a minimum of 16GB with preference for 32GB, but I'm assuming that's for the entire machine and not dedicated to just the server software itself. 

It certainly doesn't just try to eat all available memory, since I'm running 134GB of RAM on this guy. You gotta keep in mind, though, that the server has to keep track of where all the players are located, where all the NPCs nearby those players are located, as well as any structures that have been built, what base Pals are doing at any given moment, and so on. If you've ever run a Minecraft server, you'll know the requirements start to balloon like crazy as the map gets bigger and players move further apart. The same is almost certainly the case here, just further exacerbated by the game being a beta product at best.

In any case, this is definitely not something up with this particular project. I imagine it's best practice to set at least a soft memory limit on most containers, so you could do that, if your other apps are being starved by the game server, but you will want to set it to at least 16GB. Unfortunately, if you don't have an old gaming rig to use as your server, you're probably going to be better off renting a server from someone else, instead.

**Comment by chadouming** [comment]
> Mine's been running for about 4 hours and is up to ~6GB of memory usage. The system requirements in the server documentation recommend a minimum of 16GB with preference for 32GB, but I'm assuming that's for the entire machine and not dedicated to just the server software itself.
> 
> It certainly doesn't just try to eat all available memory, since I'm running 134GB of RAM on this guy. You gotta keep in mind, though, that the server has to keep track of where all the players are located, where all the NPCs nearby those players are located, as well as any structures that have been built, what base Pals are doing at any given moment, and so on. If you've ever run a Minecraft server, you'll know the requirements start to balloon like crazy as the map gets bigger and players move further apart. The same is almost certainly the case here, just further exacerbated by the game being a beta product at best.
> 
> In any case, this is definitely not something up with this particular project. I imagine it's best practice to set at least a soft memory limit on most containers, so you could do that, if your other apps are being starved by the game server, but you will want to set it to at least 16GB. Unfortunately, if you don't have an old gaming rig to use as your server, you're probably going to be better off renting a server from someone else, instead.

I'm running my server with 16GB ram allocated. With 3 players, took roughly 6 hours before restarting starving on memory. With 11 players, it's ~2hrs. Loosing 3-4 secs every 2 hours is not that bad, but it still feel bad when it happens lol.

**Comment by thijsvanloef** [comment]
as @AROAH1337 stated, this is not something I will be able to fix, marking it `wontfix` and closing the issue
