### ISSUE TITLE
Support migrate from existing data

### ISSUE THREAD

**Issue by Ericwww** [thijsvanloef/palworld-server-docker#96]
Thank you for providing the docker image and compose file.

I migrated my existing server to use docker deployment today.
Recovering from existing data requires some manual operations. I think this operation can be integrated into the docker image to facilitate users to migrate servers.

I saw a [migration solution](https://bbs.nga.cn/read.php?tid=39075608&rand=541) from a game forum in China like this:

```shell
cp -r oldServer:steamapps/common/PalServer/Pal/Saved/SaveGames/0/{SERVER_NAME}/ newServer:steamapps/common/PalServer/Pal/Saved/SaveGames/0/{SERVER_NAME}/
```

And then 

```shell
sed -i "s/DedicatedServerName=[A-Z0-9]*/DedicatedServerName={SERVER_NAME}/" /palworld/Pal/Saved/Config/LinuxServer/GameUserSettings.ini
```

Now I'm not sure if the `GameUserSettings.ini` file is generated before starting the game server. 
If so this problem would be much simpler. 
If not, I have no idea how to solve this problem.

I can't test it because I'm with Apple Silicon.

If anyone has ideas, welcome to discuss.

**Comment by Jortana** [comment]
I used to run the server directly on Windows, but later I migrated it to a Docker environment.

My approach was to first enter the new server and create a character, in order to let my new server generate some necessary files. 

Then, I would change the DedicatedServerName in the `GameUserSettings.ini` file of the new server. Also, I deleted the `steamapps/common/PalServer/Pal/Saved/SaveGames/0/{SERVER_NAME}/` folder in the new server and replace it with the folder from the old server.

By doing this and restarting the server, All players could play normally.
